version: '3'
services:
  app:
    build: .
    env_file:
      - .env
    ports: 
      - 8080:8080 
    depends_on:
      - postgres
      - redis          
    networks:
      - fullstack
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER_NAME}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    networks:
      - fullstack
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - fullstack                  

networks:
  fullstack:
    driver: bridge